#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename	"Inharmonic.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Inharmonic VST3 (64Bit)"
#else
#define stringFileDescription	"Inharmonic VST3"
#endif
#define stringCompanyName		"mogesystem\0"
#define stringLegalCopyright	"(C) 2025 mogesystem"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
